"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
'''
from setuptools import setup

APP = ['PyGuy.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
'''
  
from distutils.core import setup
import py2exe

#windows = no command prompt. console = command prompt
setup(
    windows = [
        {
            "script": "GFileTrade.py",
            "icon_resources": [(0, "froicon.ico")]
        }
    ]#,


#console=['PyGuy.py']

      )
